---
title: "Data Normalization and FC Calculation"
author: "Elias"
format: html
---

```{r loading data}
proteomic_data_cleaned <- read.csv("/cellfile/cellnet/mESC_differentiation/translation_on_demand/data/processed/proteomic_data_cleaned.csv", check.names = FALSE)

transcriptomic_data_cleaned <- read.csv("/cellfile/cellnet/mESC_differentiation/translation_on_demand/data/processed/transcriptomic_data_cleaned.csv", check.names = FALSE)
```

```{r getting gene exon lengths}
 # Load necessary libraries
library(biomaRt)
library(dplyr)
library(tidyr)

# Use the Ensembl BioMart and select the most recent release for mouse
ensembl <- useEnsembl(biomart = "ensembl", dataset = "mmusculus_gene_ensembl")

# Get exon data for all genes: exon starts, exon ends, and gene IDs
exon_data <- getBM(attributes = c('ensembl_gene_id', 'exon_chrom_start', 'exon_chrom_end'),
                  mart = ensembl)

# Calculate unique exon lengths for each gene
# Group by gene, then extract unique positions covered by exons
gene_exon_lengths <- exon_data %>%
 rowwise() %>%
 mutate(exon_positions = list(seq(exon_chrom_start, exon_chrom_end))) %>%
 ungroup() %>%
 dplyr::select(ensembl_gene_id, exon_positions) %>%
 unnest(cols = c(exon_positions)) %>%
 distinct(ensembl_gene_id, exon_positions) %>%
 group_by(ensembl_gene_id) %>%
 summarise(Exonic_Length = n())

# Save the gene exon lengths to a CSV file
write.csv(gene_exon_lengths, "/cellfile/cellnet/mESC_differentiation/translation_on_demand/data/reference/mouse_gene_exon_lengths.csv", row.names = FALSE)
```

```{r TPM normalization}
transcriptomic_data_cleaned <- merge(transcriptomic_data_cleaned, gene_exon_lengths, by="ensembl_gene_id") 

transcriptomic_data_cleaned$Exonic_Length <- transcriptomic_data_cleaned$Exonic_Length / 1000

row.names(transcriptomic_data_cleaned) <- transcriptomic_data_cleaned$ensembl_gene_id


transcriptomic_data_cleaned[, 3:(ncol(transcriptomic_data_cleaned) - 1)] <- transcriptomic_data_cleaned[, 3:(ncol(transcriptomic_data_cleaned) - 1)] / transcriptomic_data_cleaned$Exonic_Length

RPK <- transcriptomic_data_cleaned[, 3:(ncol(transcriptomic_data_cleaned) - 1)]

TPM_scaling_factors <- colSums(RPK) / 1e6

TPM <- sweep(RPK, 2, TPM_scaling_factors, "/")

TPM_log2 <- log2(TPM + 1)

TPM_log2$GeneID <- transcriptomic_data_cleaned$GeneID
TPM_log2$ensembl_gene_id <- transcriptomic_data_cleaned$ensembl_gene_id

write.csv(RPK, file = "/cellfile/cellnet/mESC_differentiation/translation_on_demand/data/processed/transcriptomic_data_RPK.csv")

write.csv(TPM, file = "/cellfile/cellnet/mESC_differentiation/translation_on_demand/data/processed/transcriptomic_data_TPM.csv")

write.csv(TPM_log2, file = "/cellfile/cellnet/mESC_differentiation/translation_on_demand/data/processed/transcriptomic_data_TPM_log2.csv")

```

```{r merging data}
proteome_and_transcriptome_TPM_log2 <- merge(proteomic_data_cleaned, TPM_log2, by="GeneID") %>% relocate(ensembl_gene_id, .after = GeneID) %>% 
  setNames(c("GeneID", "EnsemblID", "UniprotID", "0m_protein", "1h_protein", "6h_protein", "12h_protein", "24h_protein", "36h_protein", "48h_protein", "72h_protein", "0m_transcript", "1h_transcript", "6h_transcript", "12h_transcript", "24h_transcript", "36h_transcript", "48h_transcript", "72h_transcript"))

write.csv(proteome_and_transcriptome_TPM_log2, file = "/cellfile/cellnet/mESC_differentiation/translation_on_demand/data/processed/proteome_and_transcriptome_TPM_log2.csv")
```

```{r FC calculation}
calculating_FC_between_time_points <- function(count_matrix) {
  
  # Extract the time points from the column names
  time_points <- colnames(count_matrix)
  
  # Initialize an empty dataframe with the same number of rows as count_matrix
  FC_df <- data.frame(matrix(ncol = 0, nrow = nrow(count_matrix)))
  
  # Calculate fold changes between consecutive time points
  for(i in (2:ncol(count_matrix)-1)){
  
    # Calculate fold change between current column and previous column
    FC_column <- count_matrix[,i+1] - count_matrix[,i]
    
    # Add the fold-change column to FC_df with the appropriate name
    FC_df[[paste0("FC_", time_points[i], "_to_", time_points[i+1])]] <- FC_column
  }
  
  # Set row names of FC_df to match the original count_matrix
  rownames(FC_df) <- rownames(count_matrix)
  
  return(FC_df)
}


TPM_log2_FC <- calculating_FC_between_time_points(TPM_log2[,1:8])
TPM_log2_FC$GeneID <- TPM_log2$GeneID 


proteomic_data_FC <- calculating_FC_between_time_points(proteomic_data_cleaned[,3:10])
proteomic_data_FC$GeneID <- proteomic_data_cleaned$GeneID


write.csv(TPM_log2_FC, file = "/cellfile/cellnet/mESC_differentiation/translation_on_demand/data/processed/TPM_log2_FC.csv")
write.csv(proteomic_data_FC, file = "/cellfile/cellnet/mESC_differentiation/translation_on_demand/data/processed/proteomic_data_FC.csv")

```
