---
title: "Over-Representation Analysis"
author: "Elias"
format: html
editor: visual
---

```{r}
TOD_candidates <- jsonlite::read_json("/cellfile/cellnet/mESC_differentiation/translation_on_demand/results/translation_on_demand_candidates_1_threshold.json")

background_genes <- read.csv("/cellfile/cellnet/mESC_differentiation/translation_on_demand/results/background_genes.csv", check.names = F, row.names = 1)
```

```{r preparing data for DAVID analysis}
write.csv(TOD_candidates$TOD_candidates_0m_to_1h, file = "/cellfile/cellnet/mESC_differentiation/translation_on_demand/results/translation_on_demand_candidates_0m_to_1h.csv")

write.csv(TOD_candidates$TOD_candidates_1h_to_6h, file = "/cellfile/cellnet/mESC_differentiation/translation_on_demand/results/translation_on_demand_candidates_1h_to_6h.csv")

write.csv(TOD_candidates$TOD_candidates_6h_to_12h, file = "/cellfile/cellnet/mESC_differentiation/translation_on_demand/results/translation_on_demand_candidates_6h_to_12h.csv")

write.csv(TOD_candidates$TOD_candidates_12h_to_24h, file = "/cellfile/cellnet/mESC_differentiation/translation_on_demand/results/translation_on_demand_candidates_12h_to_24h.csv")

write.csv(TOD_candidates$TOD_candidates_24h_to_36h, file = "/cellfile/cellnet/mESC_differentiation/translation_on_demand/results/translation_on_demand_candidates_24h_to_36h.csv")

write.csv(TOD_candidates$TOD_candidates_36h_to_48h, file = "/cellfile/cellnet/mESC_differentiation/translation_on_demand/results/translation_on_demand_candidates_36h_to_48h.csv")

write.csv(TOD_candidates$TOD_candidates_48h_to_72h, file = "/cellfile/cellnet/mESC_differentiation/translation_on_demand/results/translation_on_demand_candidates_48h_to_72h.csv")
```

```{r GO BP Over-Representation Analysis}
BP_plots <- list()
for (i in seq_along(TOD_candidates)){
  
go_enrich_BP <- clusterProfiler::enrichGO(
    gene = TOD_candidates[[1]],  
    universe = background_genes$x,
    OrgDb = org.Mm.eg.db::org.Mm.eg.db, 
    keyType = "SYMBOL",                
    ont = "BP",                        
    pvalueCutoff = 0.5,               
    qvalueCutoff = 0.5,               
    readable = TRUE                    
)

BP_plots[[1]] <- enrichplot::dotplot(go_enrich_BP, showCategory = 10, title = paste0("GO BP Enrichment Analysis for ", names(TOD_candidates)[1]))
}

patchwork::wrap_plots(BP_plots)
```

```{r GO CC Over-Representation Analysis}
CC_plots <- list()
for (i in 1:5){
  
go_enrich_CC <- clusterProfiler::enrichGO(
    gene = TOD_candidates[[i]],            
    OrgDb = org.Mm.eg.db::org.Mm.eg.db, 
    keyType = "SYMBOL",                
    ont = "CC",                        
    pvalueCutoff = 0.05,               
    qvalueCutoff = 0.05,               
    readable = TRUE                    
)

CC_plots[[i]] <- enrichplot::dotplot(go_enrich_CC, showCategory = 10, title = paste0("GO CC Enrichment Analysis for ", names(TOD_candidates)[i]))
}

patchwork::wrap_plots(CC_plots)
```

```{r GO MF Over-Representation Analysis}
MF_plots <- list()
for (i in seq_along(TOD_candidates)){
  
go_enrich_MF <- clusterProfiler::enrichGO(
    gene = TOD_candidates[[i]],            
    OrgDb = org.Mm.eg.db::org.Mm.eg.db, 
    keyType = "SYMBOL",                
    ont = "MF",                        
    pvalueCutoff = 0.05,               
    qvalueCutoff = 0.05,               
    readable = TRUE                    
)

MF_plots[[i]] <- enrichplot::dotplot(go_enrich_MF, showCategory = 10, title = paste0("GO MF Enrichment Analysis for ", names(TOD_candidates)[i]))
}

patchwork::wrap_plots(MF_plots)

```
